name: CICD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build

build-backend:
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    
    - name: Make mvnw executable
      run: chmod +x mvnw
      working-directory: backend
    
    - name: Build backend
      run: ./mvnw clean package
      working-directory: backend

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build docker images
        run: docker compose build
